<a href="https://colab.research.google.com/github/jeong1117/study_DL/blob/main/1_5_%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [24]:
# 넘파이 배열 생성 - ny.array() 메서드
# 리스트를 인수로 넘겨받아 ndarray 생성

x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [25]:
# 넘파이 배열끼리 산술연산 가능
# 단, 원소의 수가 같아야 각 원소에 대해 행해짐

y = np.array([2.0, 4.0, 6.0])
x+y

array([3., 6., 9.])

In [26]:
x-y

array([-1., -2., -3.])

In [27]:
x*y

array([ 2.,  8., 18.])

In [28]:
x/y

array([0.5, 0.5, 0.5])

In [29]:
# 넘파이 배열과 스칼라값(수치 하나)로 산술연산 가능
# 스칼라값과 원소별로 한번씩 수행 - 브로드캐스트

x = np.array([1.0, 2.0, 3.0])
x / 2.0

array([0.5, 1. , 1.5])

In [30]:
# 넘파이 다차원배열

A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [32]:
# 다차원 행렬의 형상 확인

A.shape

(2, 2)

In [33]:
# 행렬에 담긴 원소의 자료형 확인

A.dtype

dtype('int64')

In [37]:
# 형상이 같은 행렬끼리 산술연산 가능
# 스칼라값도 연산 가능 - 브로드캐스트

B = np.array([[3, 0], [0, 6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [38]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [39]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

In [40]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [41]:
X[0]

array([51, 55])

In [42]:
X[0][1]

55

In [43]:
for row in X:
  print(row)

[51 55]
[14 19]
[0 4]


In [45]:
# 1차원 배열로 평탄화

X = X.flatten()
print(X)

[51 55 14 19  0  4]


In [46]:
# 인덱스가 0, 2, 4인 원소

X[np.array([0, 2, 4])]

array([51, 14,  0])

In [47]:
# 특정 조건을 만족하는 원소만

X[X>15]

array([51, 55, 19])